//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 技术平台公共类库
//  @ File Name : appbase.h
//  @ Date : 2013/8/15
//  @ Author : disp
//
//


#if !defined(_CAPPBASE_H)
#define _CAPPBASE_H

#include <iostream>
#include "gtwsv.h"
#include "mymutex.h"

class CAppBase
{
public:	
	CAppBase(void);
    virtual ~CAppBase(void);
    
public:
    virtual int Run(int,char**);		//主处理入口
    
protected:
    virtual int PreProcess(int,char**);	//预处理
    virtual int Process();				//实际处理
    virtual int Finish(int);			//收尾
    
protected:
    virtual void ShowVersion();			//显示版本
    virtual void ShowHelp();			//显示帮助
    
public:
	static char* GetAppName();			//获取当前程序名称
	static char* GetUserName();			//获取用户名称
	static char* GetGroupName();		//获取用户属组名称
	
protected:
	static CString 	m_strAppName;
	CShmAccess	m_ShmAccess;
	CMyMutex    m_Mutex; 	
};

#endif  //_CAPPBASE_H
