//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 技术平台公共类库，自定义格式的转换（金额，利率、税率等）
//  @ File Name : amountformat.h
//  @ Date : 2014/11/10
//  @ Author : disp
//
//


#if !defined(_CAMOUNTFORMAT_H)
#define _CAMOUNTFORMAT_H

#define AMOUNT_ADDSIGN_NULL         0
#define AMOUNT_ADDSIGN_FRONT        1
#define AMOUNT_ADDSIGN_REAR         2
#define AMOUNT_ADDSIGN_FRONTDASH    3
#define AMOUNT_ADDSIGN_REARDASH     4

#include "util/string.h"

class CAmountFormat 
{
public:	
	CAmountFormat(void);
	virtual ~CAmountFormat(void);

public:
    double  ConvertInParam(const char* szAmount,const char* szFormat);      //转换string -> double，
    CString ConvertOutParam(double dAmount,const char* szFormat);           //转换double -> string，

protected:
    /*
        //类似SQL语句中数据类型Decimal(n,m)，表示数值中共有n位数，其中整数n-m位，小数m位，n不包含符号位
        
        Z(15)9.999      15, 1,3,true  ,NULL
        Z(14).99999     14, 0,5,true  ,NULL
        9(14)V999S      0 ,14,3,false ,REAR
        S9(14)V999      0 ,14,3,false ,FRONT
        9(12)V9(5)S     0 ,12,5,false ,REAR
    */
    struct AFormat              //Z(10)99.999S = Z(10)9(2).999S
    {
        int nCompZero;          //压缩位长
        int nIntWidth;          //整数位长
        int nPrecision;         //小数位长
        bool bDecimalPoint;     //小数点
        int nAddSign;           //正负号
    };
    
protected:
    int ParseFormat(const char* szFormat,struct AFormat* pstFormat); 
    int CountNumNine(CString& strFormat);    
    
    CString ConvertD2S(double dAmount,const struct AFormat* pstFormat);
    double  ConvertS2D(const char* szAmount,const struct AFormat* pstFormat);
 		
};


#endif  //_CAMOUNTFORMAT_H
