//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 日期跨度处理类
//  @ File Name : datetimespan.cpp
//  @ Date : 2014/5/6
//  @ Author : disp
//
//

#include "datetimespan.h"


CDateTimeSpan::CDateTimeSpan()
{

}

CDateTimeSpan::CDateTimeSpan(const CDateTimeSpan & dtsSrc)
{
    m_dtStart   = dtsSrc.GetDTStart();
    m_dtEnd     = dtsSrc.GetDTEnd();
}    
    
CDateTimeSpan::CDateTimeSpan(const CDateTime & dtStart , const CDateTime & dtEnd)
{
    m_dtStart   = dtStart;
    m_dtEnd     = dtEnd;    
}
    
CDateTimeSpan::~CDateTimeSpan()
{

}

int CDateTimeSpan::GetYMDDetail(int& nYear,int& nMonth,int& nDay)	    //以年月日的方式表示时间跨度期
{
    if(!m_dtStart.IsValid() || !m_dtEnd.IsValid())  //无效日期
        return -1;
    if(m_dtEnd < m_dtStart) //结束日期小于开始日期
        return -1;
   
    nYear = 0;
    if( (m_dtEnd.GetMonth() > m_dtStart.GetMonth()) 
    || ( m_dtEnd.GetMonth() == m_dtStart.GetMonth() && m_dtEnd.GetDay() >= m_dtStart.GetDay() ) )   
        nYear = m_dtEnd.GetYear() - m_dtStart.GetYear();
    else
        nYear = m_dtEnd.GetYear() - m_dtStart.GetYear()-1;    

        
    nMonth=0;
    if(m_dtEnd.GetMonth() >= m_dtStart.GetMonth())
        nMonth = m_dtEnd.GetMonth() - m_dtStart.GetMonth();
    else
        nMonth = m_dtEnd.GetMonth() - m_dtStart.GetMonth()+12;

                
    nDay=0;
    if(m_dtEnd.GetDay() >= m_dtStart.GetDay())  //结束日数 大于等于 开始日数
    {
        nDay = m_dtEnd.GetDay() - m_dtStart.GetDay();
        
    }
    else //结束日数 小于 开始日数
    {
        nMonth -= 1;    //月数调整-1
        
        int nTmpDays = 0;   //上个月的总天数（可能为闰月）
        if(m_dtEnd.GetMonth() == CDateTime::M_JAN)  //如果结束日期是1月份
            nTmpDays = CDateTime::DaysInMonth(m_dtEnd.GetYear()-1, CDateTime::M_DEC );
        else
            nTmpDays = CDateTime::DaysInMonth(m_dtEnd.GetYear(), m_dtEnd.GetMonth()-1 );    
                
        nDay = nTmpDays+m_dtEnd.GetDay()- m_dtStart.GetDay();   

          
    } 

    return 0;
    
}

int CDateTimeSpan::GetTotalYears(int& nYears)	                        //以年方式表示时间跨度
{
    if(!m_dtStart.IsValid() || !m_dtEnd.IsValid())  //无效日期
        return -1;
    if(m_dtEnd < m_dtStart) //结束日期小于开始日期
        return -1;
   
    nYears = 0;
    if( (m_dtEnd.GetMonth() > m_dtStart.GetMonth()) 
    || ( m_dtEnd.GetMonth() == m_dtStart.GetMonth() && m_dtEnd.GetDay() >= m_dtStart.GetDay() ) )   
        nYears = m_dtEnd.GetYear() - m_dtStart.GetYear();
    else
        nYears = m_dtEnd.GetYear() - m_dtStart.GetYear()-1;    

    return 0;
}

int CDateTimeSpan::GetTotalMonths(int& nMonths)	                        //以月方式表示时间跨度
{
    if(!m_dtStart.IsValid() || !m_dtEnd.IsValid())  //无效日期
        return -1;
    if(m_dtEnd < m_dtStart) //结束日期小于开始日期
        return -1;
    
    nMonths=0;
    
    //先假设结束日 大于等于 开始日 if(m_dtEnd.GetDay() >= m_dtStart.GetDay())
    {
        if( m_dtEnd.GetMonth() >= m_dtStart.GetMonth()) 
            nMonths = (m_dtEnd.GetYear() - m_dtStart.GetYear())*12 + (m_dtEnd.GetMonth() - m_dtStart.GetMonth());
        else
            nMonths = (m_dtEnd.GetYear() - m_dtStart.GetYear()-1)*12 + (m_dtEnd.GetMonth() - m_dtStart.GetMonth())+12;   

    }
    
    if(m_dtEnd.GetDay() < m_dtStart.GetDay()) //结束日 小于 开始日
        nMonths -= 1;
    
    return 0;

}

int CDateTimeSpan::GetTotalDays(int& nDays)	                            //以天方式表示时间跨度 
{
    if(!m_dtStart.IsValid() || !m_dtEnd.IsValid())  //无效日期
        return -1;
    if(m_dtEnd < m_dtStart)                         //结束日期小于开始日期
        return -1;
    
    nDays=0;
    
    for(int y=m_dtStart.GetYear();y<m_dtEnd.GetYear();y++)              //先计算整年的天数
        nDays += CDateTime::DaysInYear(y);
            
    nDays = nDays + m_dtEnd.GetDayInYear()-m_dtStart.GetDayInYear();    //再进行具体计算
    
        
    return 0;
}

