//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 技术平台公共类库
//  @ File Name : appbase.cpp
//  @ Date : 2013/8/15
//  @ Author : disp
//
//

#include <iostream>
#include "appbase.h"

CString CAppBase::m_strAppName="";

CAppBase::CAppBase()
{
	//m_strAppName="";
}

CAppBase::~CAppBase()
{

}

int CAppBase::Run(int argc, char *argv[])
{
	int nRet = PreProcess(argc,argv);
	if(nRet < 0)
		return -1;
		
	int nProcess = Process();
	
	nRet = Finish(nProcess);
	
	return nRet;
	
}

int CAppBase::PreProcess(int argc, char *argv[])
{
	m_strAppName = argv[0];
	
	return 0;
}

int CAppBase::Process()
{
	return 0;
}

int CAppBase::Finish(int nProcess)
{
	return 0;
}


char* CAppBase::GetAppName()
{
	return m_strAppName.c_str();
}

char* CAppBase::GetUserName()
{
	uid_t uid = getuid();
	struct passwd *pwd = getpwuid(uid);
	return (pwd ? pwd->pw_name : NULL);

}

char* CAppBase::GetGroupName()
{
	gid_t gid = getgid();
	struct group *grp = getgrgid(gid);
	return (grp ? grp->gr_name : NULL);				
	
}

void CAppBase::ShowVersion()
{
   string osname="UNIX";
   
#ifdef WIN32
    osname="Windows";
#endif
#ifdef __LINUX__
    osname="LINUX";
#endif
#ifdef __HPUX__
    osname="HP-UX";
#endif
#ifdef __SUN__
    osname="Sun Solaris";
#endif	

    cout<<endl;
	cout<<"Version 1.0 for "<<osname<<"  -Complie Time :"<<__DATE__<<" "<<__TIME__<<endl;

}

void CAppBase::ShowHelp()
{
}