//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 技术平台公共类库
//  @ File Name : mintcpio.h
//  @ Date : 2013/8/15
//  @ Author : disp
//
//


#if !defined(_CMINTCPIO_H)
#define _CMINTCPIO_H

#include "gtwsv.h"

class CMintcpio
{
public:
	CMintcpio(void);
 	CMintcpio(int socket);
 	~CMintcpio(void);
    
 public:
 	int ReadMsg(byte *msg,int* msglen);         //原始发送
    int WriteMsg(byte *msg,int msglen);         //原始接收
 	int Read(MINTCPIO_DATA *data,int* datalen); //舍弃TCPHEADER
    int Write(MINTCPIO_DATA *data,int datalen); //添加TCPHEADER
    void Finish();
 	
 public:
 	void SetClientSD(int socket){ m_client_sd = socket; };
 	int  GEtClentSD() { return m_client_sd; };
 	 	
 protected:
 	int m_client_sd;
 	int MINgetsbyte(byte *cbuf);
	int MINputsbyte(char msgbyte);
	
};

#endif  //_CMINTCPIO_H
