//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 技术平台公共类库
//  @ File Name : tcpmain.h
//  @ Date : 2013/8/15
//  @ Author : disp
//
//


#if !defined(_CTCPMAIN_H)
#define _CTCPMAIN_H

#include "appbase.h"

#define CMD_START 	0
#define CMD_STOP 	1
#define CMD_RESTART	2
#define CMD_STATUS	3

#define RET_OK 		0
#define RET_BAD 	1
#define RET_MPEXIT	2

class CTcpMain : public CAppBase
{
public:	
	CTcpMain(void);
    virtual ~CTcpMain(void);
    
protected:
    virtual int PreProcess(int,char**);
    virtual int Process();
    virtual int Finish(int);
 
protected:
    virtual void ShowHelp();
    int MakeMPDaemon();
    int DoService();
    int ProcessRequest();
    
    static bool m_bMPWSEndFlag;
    
    //bool m_bWSEndFlag,m_bWSLastMessage;
    int m_client_sd;
	 
   	
private:
	int	m_nCmdType;
	bool m_bDaemon;
	int m_nListenPort;

	
public:		
	static void SignalCleanup(int sig);
};

#endif  //_CTCPMAIN_H
