//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 技术平台公共类库
//  @ File Name : shmbase.h
//  @ Date : 2013/7/17
//  @ Author : disp
//
//


#if !defined(_CSHMBASE_H)
#define _CSHMBASE_H

#include <sys/shm.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/stat.h>
#include "util/iniconfig.h"
#include "util/string.h"

#define		REGION_ENV		"NCBS_DQPTYPE"				// environment variable for region_id 
#define		SYS_NUM_ENV		"NCBS_SYSNUM"				// environment variable for system_id
#define 	SHM_FLAGMASK	(key_t)(0x8A000000)
#define		DSAREA_ACCESS	0660						// rw for user only 

class CShmBase
{
public:
		CShmBase();
		CShmBase(const char* pFilePath);
		~CShmBase();
		
public:
    int InitCfg(const char* pFilePath);
    void UninitCfg();

protected:
    key_t GetAreaKey(int dsflag,char chSysNum=' ');
    CString GetCfgData(const char* pSection,const char* pKey); 
    CString GetCfgData(const char* pSection,const char* pKey,int nIndex); 
           	
protected:
    static CIniConfig m_config;

};

#endif  //_CSHMBASE_H
