//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 技术平台公共类库 区域读写锁
//  @ File Name : arealock.h
//  @ Date : 2013/6/20
//  @ Author : disp
//
//	
//注：读写锁适合于对数据结构的读次数比写次数多得多的情况。 读模式锁共享, 写模式锁独占。

#if !defined(_CAREALOCK_H)
#define _CAREALOCK_H

#define	AREA_READ_SEM		0		/* array offset */
#define	AREA_UPDATE_SEM	1

#define	LOCK_BINARY			-1	/* operation value */
#define	UNLOCK_BINARY		1
#define	LOCK_MULTI			1	
#define	UNLOCK_MULTI		-1	
#define	EMPTY_MULTI			0

#define	MULTI_INIT			0
#define	BINARY_INIT			1

#include "mutexlock.h"


class CAreaLock
{
public:
    CAreaLock();
    ~CAreaLock();
    
public:    
    int Create(key_t key);			//创建新的区域读写锁
    int Select(key_t key);			//选择已有的区域读写锁
    int LockUpdate();				//写模式加锁
    int LockRead();					//读模式加锁
    int UnlockUpdate();				//写模式解锁
    int UnlockRead();				//读模式解锁
    int Destroy();					//销毁区域读写锁
    
protected:
    int m_nSemId;
    int TryWait(int num, int block);
};

#endif  //_CAREALOCK_H
