//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 技术平台公共类库 支持CDict消息队列
//  @ File Name : dictqueue.h
//  @ Date : 2013/6/13
//  @ Author : disp
//
//


#if !defined(_CDICTQUEUE_H)
#define _CDICTQUEUE_H

#include "queue.h"

class CDict;

class CDictQueue : public CQueue
{
public:
	CDictQueue();
	~CDictQueue();	
	
public:
    int SendDict(CDict* pDict);
    int SendDict_NOWAIT(CDict* pDict);
    int ReceiveDict(CDict* pDict);
    int ReceiveDict_NOWAIT(CDict* pDict);
};

#endif  //_CDICTQUEUE_H
