//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 技术平台公共类库 基于信号量的互斥锁
//  @ File Name : mutexlock.h
//  @ Date : 2013/6/20
//  @ Author : disp
//
//


#if !defined(_CMUTEXLOCK_H)
#define _CMUTEXLOCK_H

#include <sys/types.h>
#include <sys/ipc.h>	
#include <sys/sem.h>
#include <sys/ipc.h>

union semun {
      int val;
      struct semid_ds *buf;
      ushort *array;
};


class CMutexLock
{
public:
    CMutexLock();
    ~CMutexLock();

public:
    int Create(key_t key);			//创建新的互斥锁
		int Select(key_t key);			//选择已有的互斥锁
    int Lock();									//加锁
		int Unlock();								//解锁
    int Destroy();							//销毁互斥锁
    
protected:
    int m_nSemId;
    int TryWait(int block=1);		//测试    
};

#endif  //_CMUTEXLOCK_H
