//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 技术平台公共类库
//  @ File Name : simplelog.h
//  @ Date : 2013/8/1
//  @ Author : disp
//
//


#if !defined(_CSIMPLELOG_H)
#define _CSIMPLELOG_H

#include <stdio.h>
#include <string>
#include <iostream>
#include <fstream>

using namespace std;

class CSimpleLog
{
public:
	CSimpleLog(void);
	~CSimpleLog(void);

protected:
	//ofstream m_fo;
	FILE *m_pFile,*m_pLockFile;
	string m_sErrorStr;
	string m_sLogFile,m_sLogFileOld,m_sLockFile;
	long m_nMaxSize;

public:
	int Init(const string sLogFile,const string sLogFileOld,const string sLockFile,long nMaxSize=5120);
    int Write(const string sData);
    int Write(const char* pData);
    void Uninit();
	const string GetErrorStr(){ return m_sErrorStr; };

protected:	
	bool GetCurrentDateTime(string& sDate,string& sTime);
	
};

#endif  //_CSIMPLELOG_H
